### ISSUE TITLE
Use military 24H clock or display AM/PM

### ISSUE THREAD

**Issue by matt6frey** [arunghosh/react-time-line#167]
The component looks great but doesn't differentiate between AM/PM. or show 24 hour clock

**This example**
```
<Timeline items={[
          {ts: new Date(), text: 'date obj'},
          {ts: `${new Date()}`, text: 'interpolated'},
          {ts: new Date().toISOString(), text: 'iso'},
          {ts: new Date().toGMTString(), text: 'gmt'},
          {ts: new Date().toDateString(), text: 'date'}
        ]} />
```
**Outputs the times**
date obj = 03:15
interpolated = 03:15
iso = 03:15
gmt = 03:15
date = 12:00

 - Regardless of morning or afternoon/evening (Tested this at separate times from 8 am to 3pm)

Request to fix is in the `Timeline.js`, line 13: change `date.format('hh:mm'),` to `date.format('HH:mm'),` or `date.format('hh:mm a')`.

Alternatively, allow users option to pass time format specified in module docs or by referring user to Moment.js docs.

**Comment by sahilpaudel-pe** [comment]
I have the same requirement.

**Comment by NilsBaumgartner1994** [comment]
Same

**Comment by arunghosh** [comment]
`v3.0.0` has `format` property.  For formatting options [check momentjs format docs](https://momentjs.com/docs/#/displaying/format/).

```
// default format is "hh:mm"
<Timeline items={events} format="hh:mm a" />
```

@matt6frey Sorry for the delay. Thank you for your suggestions it helped to make the changes easily.

**Comment by sahilpaudel-pe** [comment]
I think the version you meant is v0.3.0.

> `v3.0.0` has `format` property. For formatting options [check momentjs format docs](https://momentjs.com/docs/#/displaying/format/).
> 
> ```
> // default format is "hh:mm"
> <Timeline items={events} format="hh:mm a" />
> ```
> 
> @matt6frey Sorry for the delay. Thank you for your suggestions it helped to make the changes easily.

**Comment by arunghosh** [comment]
@sahilpaudel-pe Sorry. The version is as you mentioned `v0.3.0`.

**Comment by matt6frey** [comment]
@arunghosh My pleasure! It's a really helpful package. Thanks for looking into this
